:numbered:
:toc: macro
:sectanchors:


:SCREENSHOOT_WITDH: 300

:APB_02_LABEL: Two Motors With L293D
:APB_02_LINK: https://www.tinkercad.com/things/8cWFfmivo2U-two-motors-with-l293d
:APB_02_BASENAME: Two Motors With L293D
:APB_02_INO: https://github.com/AsmaAbdullah1998/Two-DC-Motors-With-L293D/blob/main/Two%20Motors%20With%20L293d.ino 
:APB_02_IMG: Two Motors With L293d.png

:APB_03_LABEL: Eye Led Robotic 
:APB_03_LINK: https://www.tinkercad.com/things/aSQ4MNUM8o0-ledeye-robotic-
:APB_03_BASENAME: Eye Led Robotic 
:APB_03_INO: https://github.com/AsmaAbdullah1998/Five-Motors-Circuit/blob/main/circuit2.ino
:APB_03_IMG: circuit2.png



= Two Motors With L293D (Tinkercad)



== Two Motors With L293D
**This circuit is just about controlling Two Motors by L293D. Simply:)**


==== {APB_02_LABEL}

|===
| LINKS | SCREENSHOOT
a|
- **Code** : link:{APB_02_INO}[]
- **Tinkercad project** : {APB_02_LINK}
a|image::{APB_02_IMG}[link={APB_02_LINK}, width={SCREENSHOOT_WITDH}]
|===

== Eye Led Robotic 
** This circuit is about creating Two single eye Neopixel Led and for increase the fun we can imagine the seven segement display is the nose and the mouth is the Neopixel strip:). 
* Series Connection: The eye led is connected in series. The most efficient way to run high power LEDs is using a series circuit with a constant current LED driver. Running a series circuit helps to provide the same amount of current to each LED. This means each LED in the circuit will be the same brightness and will not allow a single LED to hog more current than another. When each LED is receiving the same current it helps eliminate issues like thermal runaway.


==== {APB_03_LABEL}

|===
| LINKS | SCREENSHOOT
a|
- **Code** : link:{APB_03_INO}[]
- **Tinkercad project** : {APB_03_LINK}
a|image::{APB_03_IMG}[link={APB_03_LINK}, width={SCREENSHOOT_WITDH}]
|===





